SET IDENTITY_INSERT [dbo].[items] ON
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (1, N'1', N'Glass Food Storage', N'Durable and transparent containers ideal for storing and preserving food.', N'Durable and transparent containers ideal for storing and preserving food.', 100, 275, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\43e19e3de4e66d368f488876d54d4fca.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (2, N'2', N'Steel Mug Rack', N'A sturdy rack designed to neatly organize and display mugs.', N'Kitchen Item', 100, 50, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\717352fb282b041a865e761437a3b311.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (3, N'3', N'Mitts Potholders', N'Heat-resistant mitts and potholders for safe handling of hot cookware.', N'Kitchen Item', 100, 65, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\1e5447e1d7ac58b828aedd211d4d45be.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (4, N'4', N'Steel Brazier Pot', N'A versatile and durable pot perfect for slow cooking and braising.', N'Kitchen Item', 100, 150.5, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\f815b8d765b8b36dbc31967c7fc0ce45.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (5, N'5', N'Descascador', N'A handy peeler for effortlessly removing fruit and vegetable skins.', N'Kitchen Item', 100, 79, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\5b0a23344ae75e65ee45c6fd699de638.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (6, N'6', N'Cleaning Sponge', N'A multi-purpose sponge for effective kitchen cleaning tasks.', N'Kitchen Item', 100, 35.5, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\Cleaning Sponge.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (7, N'7', N'Silverware Set', N'A complete set of utensils for dining and serving.', N'A complete set of utensils for dining and serving.', 100, 175.5, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\Silverware Set.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (8, N'ITM20250505203007194', N'Kitchen Scale', N'A precise scale for measuring ingredients with accuracy.', N'Kitchen Item', 30, 499, NULL, N'2025-05-05', N'2025-05-06', N'2025-05-06')
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (9, N'9', N'Table Cloth', N'A decorative and protective cloth for covering dining tables.', N'A decorative and protective cloth for covering dining tables.', 100, 55.5, N'C:\Users\Woots\source\repos\OnlineShop\pictures items\Table Cloth.jpg', N'2025-05-05', N'2025-05-07', NULL)
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (53, N'10', N'Table Clothss', N'A decorative and protective cloth for covering dining tables.', N'Kitchen Item', 115, 55.5, NULL, N'2025-05-06', NULL, N'2025-05-06')
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (60, N'3456', N'Table Clothssss', N'A decorative and protective cloth for covering dining tables.', N'A decorative and protective cloth for covering dining tables.', 115, 55.5, NULL, N'2025-05-06', NULL, N'2025-05-06')
INSERT INTO [dbo].[items] ([id], [item_id], [item_name], [Description], [item_type], [item_stock], [item_price], [item_image], [date_insert], [date_update], [date_delete]) VALUES (63, N'534', N'Table Clothsss', N'A decorative and protective cloth for covering dining tables.', N'A decorative and protective cloth for covering dining tables.', 115, 55.5, NULL, N'2025-05-06', NULL, N'2025-05-06')
SET IDENTITY_INSERT [dbo].[items] OFF

-- -- -- delete all data from table
DELETE FROM inventory WHERE ProductId = 3;
DELETE FROM items WHERE item_id = 3;